/**
 * Job Role Create model representing the data structure for creating new job roles
 * This interface excludes jobRoleId as it's auto-generated by the backend
 */

export interface JobRoleCreate {
	roleName: string;
	description: string;
	responsibilities: string;
	jobSpecLink: string; // Link to Job Spec in SharePoint
	location: string;
	capability: string;
	band: string;
	closingDate: string; // ISO date string (YYYY-MM-DD)
	status: string;
	numberOfOpenPositions: number;
}
